print("##############################") 
print("#                            #") 
print("#    Muhammad Rizqan Karim   #") 
print("#       2410817110005        #") 
print("#                            #") 
print("##############################")