Nama = input("Nama                    : ")
NIM = input("NIM                     : ")
Paralel = input("Kelas Paralel           : ")
TTL = input("Tempat/Tanggal Lahir    : ")
Alamat = input("Alamat                  : ")
Hobi = input("Hobby                   : ")
HP = input("No. HP                  : ")

print(" ")
print(f"Nama                    : {Nama}")
print(f"NIM                     : {NIM}")
print(f"Kelas Paralel           : {Paralel}")
print(f"Tempat/Tanggal Lahir    : {TTL}")
print(f"Alamat                  : {Alamat}")
print(f"Hobby                   : {Hobi}")
print(f"No. HP                  : {HP}")
